Repository chevyboys/Mizuchi, pull requests merged in 2022-02, with the labels that each got.

#47 Ping all updates when any of the update roles are pinged
  modules/Module.CommandInteraction.BotMeta.js
Labels: enhancement, Difficulty: Easy, Priority: Low

#48 When someone joins the guild, don't send messages in mod logs
  modules/Module.Infrastructure.Welcome.js
  utils/Utils.Database.js
  utils/Utils.RolesLogin.js
Labels: enhancement, Difficulty: Easy, Priority: Low

#49 Pin message request bug fix
  utils/Utils.ContextMenu.Message.ModCard.js
  utils/Utils.Generic.js
Labels: bug, Difficulty: Moderate, Priority: Medium

#50 Create /repo command
  modules/Module.CommandInteraction.ServerInfo.js
Labels: enhancement, Difficulty: Easy, Priority: Low

#51 Add /link Command
  modules/Module.CommandInteraction.ServerInfo.js
Labels: enhancement, Difficulty: Easy, Priority: Low

#52 Added more memes from discord
  modules/Module.CommandInteraction.ServerInfo.js
Labels: enhancement, Difficulty: Easy, Priority: Low

#55 Added issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#56 create the /pulse command and alerts
  modules/Module.CommandInteraction.BotMeta.js
Labels: documentation, enhancement, Difficulty: Moderate, Priority: Medium
